### ISSUE TITLE
WEEK 2

### ISSUE THREAD

**Issue by WerkSimon** [Luseres/Pokebowl#2]
Flowchart kan ik niet terugvinden evenals design

Zijn dit afbeeldingen die rechten vrij zijn?

LET OP: Vrijdag is er een presentatie
--

**Comment by Luseres** [comment]
Op dit moment hebben wij een mail verstuurd naar de afbeelding eigenaren voor toestemming. Als wij hiervoor geen toestemming hebben gekregen gaan we non-copyrighted afbeeldingen gebruiken.

**Comment by Luseres** [comment]
Flowchart is toegevoegd hierbij sluit ik de issue. Als de momentele afbeelding niet gebruikt mogen worden wordt dit veranderd.
